MAT: 1A
HOST: http://polls.apiblueprint.org/

# 360fly ReST API for Thunderdome v0.1.0

This API document outlines additions or modifications to the base 360fly REST specification that are required to
achieve full functionality of version 1.5 (Thunderdome).

#Group Camera

Configure and control 360fly media capture

## Camera Preferences [/360fly/camera/preferences]

Default high-level attributes for media capture

* slow-motion: set `frameRateMultiplier` < 1
* time-lapse: set `frameRateMultiplier` > 1
* normal playback: set `frameRateMultiplier` = 1

+ Attributes (object)
 + profile: proMode (string, required, sample)
 + maxChapterDuration: 180 (number, required, sample) - Max duration, in seconds, for a chapter in a recording. 
 + maxChapterFileSize  (number, required, sample) - Max file size, in bytes, for a chapter in a recording
 + frameRateMultiplier: 1 (number, required, sample) - The ratio of frame presentation duration written in video file to the encoded frame rate

### Retrieve camera preferences [GET]
+ Response 200 (application/json)
 + Attributes (Camera Preferences)

### Modify camera preferences [PUT]
+ Attributes (object)
 + maxChapterDuration (number, optional, sample, nullable) - set no timed chaptering
 + frameRateMultiplier: .5 (number, optional, sample) - set playback frame rate to half the encoded frame rate. This is essential for slow-motion playback.
 + profile: slowMotion (string, optional, sample) - Use a profile with 60FPS encoded frame-rate. This in combination with frameRateMultiplier=.5 will give quality slow-motion.

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (object)
        + profile: slowMotion (string, required, sample)
        + maxChapterDuration (number, required, sample)
        + maxChapterFileSize (number, required, sample)
        + frameRateMultiplier: .5 (number, optional, sample)

## Camera Media Profile Collection [/360fly/camera/profiles]

+ Attributes (object)
 + proMode (object, default)
        + recordingFormat: fullRes30 (string, required)
        + audioFormat: 48KAAC4 (string, required)
        + metadataFormat: mode30fps (string, required)
        + liveviewFormat: 752sq15 (string, required)
        + photoFormat: default (string, required, default)
 + fullRes24 (object)
        + recordingFormat: fullRes24 (string, required)
        + audioFormat: 48KAAC4 (string, required)
        + metadataFormat: mode30fps (string, required)
        + liveviewFormat: 1280sq30 (string, required)
        + photoFormat: default (string, required, default)
 + almostFullRes (object)
        + recordingFormat: 2816sq30 (string,required)
        + audioFormat: 48KAAC4 (string, required)
        + metadataFormat: mode30fps (string, required)
        + liveviewFormat: 752sq15 (string, required)
        + photoFormat: default (string, required, default)
 + frontFacing1584p (object)
        + recordingFormat: 1584p30
        + audioFormat: 48KAAC4 (string, required)
        + metadataFormat: mode30fps (string, required)
        + liveviewFormat: 1280sq30 (string, required)
        + photoFormat: default (string, required, default)
 + frontFacing1440p
        + recordingFormat: 1440p30 (string, required)
        + audioFormat: 48KAAC4 (string, required)
        + metadataFormat: mode30fps (string, required)
        + liveviewFormat: 1280sq30 (string, required)
        + photoFormat: default (string, required, default)
 + slowMotion (Camera Media Profile)

### List all media profiles [GET]
+ Response 200 (application/json)
 + Attributes (Camera Media Profile Collection)

## Camera Media Profile [/360fly/camera/profiles/{name}]

Describes capture/encoding formats for recording, audio, metadata, liveview, and photo.

+ Attributes (object)
 + recordingFormat: 2032sq60 (string, required)
 + audioFormat: 48KAAC4 (string, required)
 + metadataFormat: mode60fps (string, required)
 + liveviewFormat: 752sq15 (string, required)
 + photoFormat: default (string, required, default)
 
+ Parameters
 + name (required, string, `slowMotion`)
 
### Retrieve media profile details [GET]
+ Response 200 (application/json)
 + Attributes (Camera Media Profile)

### Create or modify media profile [PUT]
+ Attributes (object)
 + recordingFormat: 1504sq60 (string, required) - Changing this profile's recording format. In this example, we lower recording resolution to give encoder enough bandwidth to do simultaneous recording and liveview in the slowMotion profile.

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (object)
        + recordingFormat: 1504sq60 (string, required)
        + audioFormat: 48KAAC4 (string, required)
        + metadataFormat: mode60fps (string, required)
        + liveviewFormat: 1280sq30 (string, required)
        + photoFormat: default (string, required, default)

### Remove media profile [DELETE]
+ Response 204

## Camera Formats Collection [/360fly/camera/formats]

The available media and metadata formats. The various formats are used to compose a profile (see `/camera/profiles`). The formats are essentially configurations for underlying media/data encoder and capture applications.

*Both recording and liveview use video formats 

+ Attributes (object)
 + video (object, required) - list of available video formats
        + Include Camera Video Formats Collection
 + audio (object, required) - list of available audio formats
        + Include Camera Audio Formats Collection
 + metadata (object, optional) - list of available meta data formats
        + Include Camera Metadata Formats Collection
 + photo (object, required) - list of available photo formats

### List all camera formats [GET]
+ Response 200 (application/json)
 + Attributes (Camera Formats Collection)

## Camera Video Formats Collection [/360fly/camera/formats/video]

+ Attributes (object)
 + fullRes30 (object)
        + resolution: 2880x2880 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 30 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 60000000 (number, required)
        + quant: 18 (number, required)
        + max_quant: 23 (number, required)
        + min_quant: 0 (number, required)
        + max_framerate: 30 (number, required)
        + min_framerate: 30 (number, required)
        + frontFacing: false (boolean, required)
 + fullRes24 (object)
        + resolution: 2880x2880 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 24 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 48000000 (number, required)
        + quant: 18 (number, required)
        + max_quant: 23 (number, required)
        + min_quant: 0 (number, required)
        + max_framerate: 30 (number, required)
        + min_framerate: 30 (number, required)
        + frontFacing: false (boolean, required)
 + 2816sq30 (object)
        + resolution: 2816x2816 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 24 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 60000000 (number, required)
        + quant: 18 (number, required)
        + max_quant: 23 (number, required)
        + min_quant: 0 (number, required)
        + max_framerate: 30 (number, required)
        + min_framerate: 30 (number, required)
        + frontFacing: false (boolean, required)
 + 752sq15 (object)
        + resolution: 752x752 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 15 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 2000000 (number, required)
        + quant: 18 (number, required)
        + max_quant: 23 (number, required)
        + min_quant: 0 (number, required)
        + max_framerate: 30 (number, required)
        + min_framerate: 30 (number, required)
        + frontFacing: false (boolean, required)
 + 1584p30 (object)
        + resolution: 2816x1584 (string, required)
        + resize: crop (string, required)
        + codec: h264 (string, required)
        + framerate: 30 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 33000000 (number, required)
        + quant: 18 (number, required)
        + max_quant: 23 (number, required)
        + min_quant: 0 (number, required)
        + max_framerate: 30 (number, required)
        + min_framerate: 30 (number, required)
        + frontFacing: true (boolean, required)
 + 1440p30 (object)
        + resolution: 2560x1440 (string, required)
        + resize: crop (string, required)
        + codec: h264 (string, required)
        + framerate: 30 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 27000000 (number, required)
        + quant: 18 (number, required)
        + max_quant: 23 (number, required)
        + min_quant: 0 (number, required)
        + max_framerate: 30 (number, required)
        + min_framerate: 30 (number, required)
        + frontFacing: true (boolean, required)
 + 2032sq60 (object)
        + resolution: 2032x2032 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 60 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 60000000 (number, required)
        + quant: 18 (number, required)
        + max_quant: 23 (number, required)
        + min_quant: 0 (number, required)
        + max_framerate: 30 (number, required)
        + min_framerate: 30 (number, required)
        + frontFacing: false (boolean, required)
 + 720p15 (object)   
        + resolution: 1280x720
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 60 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 250000 (number, required)
        + quant: 18 (number, required)
        + max_quant: 23 (number, required)
        + min_quant: 0 (number, required)
        + max_framerate: 30 (number, required)
        + min_framerate: 30 (number, required)
        + frontFacing: true (boolean, required)
 + 1504sq60 (object)
        + resolution: 1504x1504 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 60 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 33000000 (number, required)
        + quant: 18 (number, required)
        + max_quant: 23 (number, required)
        + min_quant: 0 (number, required)
        + max_framerate: 30 (number, required)
        + min_framerate: 30 (number, required)
        + frontFacing: false (boolean, required)
        
### List all video formats [GET]
+ Response 200 (application/json)
 + Attributes (Camera Video Formats Collection)
         
## Camera Video Format [/360fly/camera/formats/video/{name}]

Format of encoded video for recording and liveview

+ Attributes (object)
 + resolution: 2880x2880 (string) - resolution of encoded video
 + resize: scale (string) - resize method. options: none, scale, crop
 + codec: h264 (string)
 + framerate: 30 (number) - target framerate of encoded video (FPS)
 + keyinterval: 30 (number) - framecount between keyframes
 + ratecontrol: CVBR (string) - bit rate control method. options: NONE, VQCB, CQCB, CVBR, ADPT
 + bitrate: 60000000 (number) - maximum or target bitrate (depending on ratecontrol)
 + quant: 18 (number) - target quantization. Ranges 0~51. Higher yields more compression.
 + max_quant: 23 (number) - max quantization
 + min_quant: 0 (number) - min quantization
 + max_framerate: 30 (number) max framerate of encoded video (FPS). min 15 FPS
 + min_framerate: 30 (number) min framerate of encoded video (FPS). min 15 FPS

+ Parameters
 + name (required, string, `fullRes30`)
 
### Retrieve video format details [GET]

+ Response 200 (application/json)
 + Attributes (Camera Video Format)

### Modify video format [PUT]

+ Attributes (object)
 + resolution: 2880x2880 (string)

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (Camera Video Format)

### Remove video format [DELETE]
+ Response 204

## Camera Audio Formats Collection [/360fly/camera/formats/audio]

+ Attributes (object)
 + 48KAAC4 (object)
        + bitrate: 6400 (number, required)
        + samplerate: 4800 (number, required)
        + codec: AAC4 (string, required)

### List all audio formats [GET]
+ Response 200 (application/json)
 + Attributes (Camera Audio Formats Collection)

## Camera Audio Format [/360fly/camera/formats/audio/{name}]

+ Attributes (object)
 + bitrate: 64000 (required, number) - encoded audio bitrate
 + samplerate: 48000 (required, number) - rate audio is sampled
 + codec: AAC4 (required, string)
 
+ Parameters
 + name (required, string, `48KAAC4`)
 
### Retrieve audio format details [GET]
+ Response 200 (application/json)
 + Attributes (Camera Audio Format)

### Modify audio format [PUT]
+ Attributes (object)
 + bitrate: 64000 (number)

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (Camera Audio Format)

### Remove audio format [DELETE]
+ Response 204

## Camera Metadata Formats Collection [/360fly/camera/formats/metadata]

+ Attributes (object)
 + mode30fps (Camera Metadata Format)
 + mode60fps (object)
        + accel_mode: 2 (number, optional) - accelerometer mode 2g
        + accel_rate: 60 (number, optional) - accelerometer sample rate, 60 samples per seconds
        + gyro_mode: 1 (number, optional) - mode 1
        + gyro_rate: 60 (number, optional) 
        + magneto_mode: 1 (number, optional)
        + magneto_rate: 60 (number, optional)
        + gps_rate: 1 (number, optional)

### List all metadata formats [GET]
+ Response 200 (application/json)
 + Attributes (Camera Metadata Formats Collection)

## Camera Metadata Format [/360fly/camera/formats/metadata/{name}]

Format of metadata. Effectively a configuration for underlying sensors, events, etc.

+ Attributes (object)
 + accel_mode: 2 (number)
 + accel_rate: 30 (number)
 + gyro_mode: 1 (number)
 + gyro_rate: 30 (number)
 + magneto_mode: 1 (number)
 + magneto_rate: 30 (number)
 + gps_rate: 1 (number)
 
+ Parameters
 + name (required, string, `mode30fps`)
 
### Retrieve metadata format details [GET]
+ Response 200 (application/json)
 + Attributes (Camera Metadata Format)

### Modify metadata format [PUT]
+ Attributes (object)
 + accel_rate: 30 (number)

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (Camera Metadata Format)

### Remove metadata format [DELETE]
+ Response 204

## Camera Photo Formats [/360fly/camera/formats/photo]

+ Attributes (object)
 + normalMode (Camera Photo Format)
 + burstMode (object, required, sample)
        + resolution: 3456x3456 (string, required, default)
        + burst: true (boolean, required, default)
        + duration: 1 (number, required, default)

### Retrieve Camera Photo Formats [GET]
+ Response 200 (application/json)
 + Attributes (Camera Photo Formats)

## Camera Photo Format [/360fly/camera/formats/photo/{name}]

+ Attributes (object)
 + resolution: 3456x3456 (string, required, default) - resolution of photo
 + burst: false (boolean, required, default) - Toggle burst mode
 + duration (number, optional, default) - How long, in seconds, to take burst photos. Applies to burst mode only.

+ Parameters
 + name (required, string, `normalMode`) name of relevant camera photo format

## Liveview [/360fly/camera/liveview]

Status and settings for the 360fly `rtsp` stream.

+ Attributes
 + url: rtsp://fly.local/live1.sdp (string, required, sample) - livestream url
 + projection (Projection, required, default)

### Retrieve liveview settings [GET]
+ Response 200 (application/json)
 + Attributes (Liveview)

## Photo [/360fly/camera/photo]

Photo Capture interface. See /camera/preferences for photo format details.

### Take Photo [POST]

Returns empty response body with new photo's download link in `Location` header

+ Attributes (object)
 + burst: true (boolean, optional, sample) - Override current camera profile for this photo and take burst photo
 + duration: 3 (number, optional, sample) - Take 3 seconds worth of burst photos

+ Response 201
 + Header
 
            Location: /video/file/{photo.jpg}

## Tuning [/360fly/camera/tuning]

+ Attributes (object)
 + ae_lock: false (boolean, required) - auto exposure lock/unlock
 + saturation: 100 (number, required) - image saturation. Range 0~200
 + max_iso_sensitivity: 8000 (number, required) - image iso (which adjusts gain). Range: 1000~64000
 + awb_lock: false (boolean, required) - auto white balance lock/unlock
 + brightness: 100 (number, required) - image brightness. Range 0~200
 + ae_compensation: 100 (number, required) - compensation for auto exposure. Range: 50~200
 + contrast: 100 (number, required) - image contrast. Range 0~100
 + max_shutter: 30 (number, required) - max shutter speed. Shows denominator e.g. 30 implies 1/30 seconds. Must be >= 15

### Retrieve tuning settings [GET]
+ Response 200 (application/json)
 + Attributes (Tuning)

### Modify tuning settings [PUT]

+ Attributes (object)
        + max_shutter: 15 (number) - Increase max shutter speed to 1/15 seconds i.e. low light mode

+ Request (application/json)

+ Response 200 (application/json)
+ Attributes (object)
 + ae_lock: false (boolean, required)
 + saturation: 100 (number, required)
 + max_iso_sensitivity: 8000 (number, required)
 + awb_lock: false (boolean, required)
 + brightness: 100 (number, required)
 + ae_compensation: 100 (number, required)
 + contrast: 100 (number, required)
 + max_shutter: 15 (number, required)
 
## Projection [/360fly/camera/projection]

Camera's default projection

+ Attributes (object)
 + type: radial (string, required, default) - class of projection
 + radialMapping: ftheta (string, required, default) - name of mapping used to map angle to radius on a radial capture image
 + outerAngle: 120 (number, required, default) - Half of the vertical field of view. The max of the radialMapping's domain.
 + centerRadius: 0.5 0.5 0.5 0.5 (string, required, default) - The location and size of radial image in camera's normalized sensor coordinates

### Set Projection [PUT]

For setting projection at manufacturing. Can only be done once.

+ Request (application/json)
 + Attributes (Projection)

+ Response 200 (application/json)
 + Attributes (Projection)



