MAT: 1A
HOST: http://polls.apiblueprint.org/

# 360fly ReST API for Thunderdome

This API document outlines additions or modifications to the base 360fly REST specification that are required to
achieve full functionality of version 1.5 (Thunderdome).

# Global Response Headers

These response headers are to be included with _every_ response

+ Headers

                        X-360fly-API-Version: v0.1.0


# Group Camera

Configure and control 360fly media capture

## Camera Preferences [/360fly/camera/preferences]

Default high-level attributes for media capture

* slow-motion: set `frameRateMultiplier` < 1
* time-lapse: set `frameRateMultiplier` > 1
* normal playback: set `frameRateMultiplier` = 1

+ Attributes (object)
 + profile: proMode (string, required, default) - Current camera profile. Determines default media formats for recorded and liveview video and audio, sensordata, and photos. 
 + maxChapterDuration (number, required, sample) - Max duration, in seconds, for a chapter in a recording. 
 + maxChapterFileSize  (number, required, sample) - Max file size, in bytes, for a chapter in a recording
 + frameRateMultiplier: 1 (number, required, default) - The ratio of frame presentation duration written in video file to the encoded frame rate

### Retrieve camera preferences [GET]
+ Response 200 (application/json)
 + Attributes (Camera Preferences)

### Modify camera preferences [PUT]
+ Attributes (object)
 + maxChapterDuration: 180 (number, optional, sample) - set chapter duration to 180 seconds
 + frameRateMultiplier: .5 (number, optional, sample) - set playback frame rate to half the encoded frame rate. This is essential for slow-motion playback.
 + profile: slowMotion (string, optional, sample) - Use a profile with 60FPS encoded frame-rate. This in combination with frameRateMultiplier=.5 will give quality slow-motion.

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (object)
        + profile: slowMotion (string, required, sample)
        + maxChapterDuration: 180 (number, required, sample)
        + maxChapterFileSize (number, required, sample)
        + frameRateMultiplier: .5 (number, required, sample)

## Camera Media Profile Collection [/360fly/camera/profiles]

+ Attributes (object)
 + proMode (Camera Media Profile, required, default)
 + fullRes24 (object, required)
        + recordingFormat: fullRes24 (string, required)
        + audioFormat: 48KAAC4 (string, required)
        + sensordataFormat: mode30fps (string, required)
        + liveviewFormat: 1424sq24 (string, required)
        + photoFormat: normal (string, required, default)
 + almostFullRes (object, required)
        + recordingFormat: 2816sq30 (string,required)
        + audioFormat: 48KAAC4 (string, required)
        + sensordataFormat: mode30fps (string, required)
        + liveviewFormat: 752sq15 (string, required)
        + photoFormat: normal (string, required, default)
 + frontFacing1584p (object, required)
        + recordingFormat: 1584p30
        + audioFormat: 48KAAC4 (string, required)
        + sensordataFormat: mode30fps (string, required)
        + liveviewFormat: 720p15 (string, required)
        + photoFormat: normal (string, required, default)
 + frontFacing1440p (object, required)
        + recordingFormat: 1440p30 (string, required)
        + audioFormat: 48KAAC4 (string, required)
        + sensordataFormat: mode30fps (string, required)
        + liveviewFormat: 720p15 (string, required)
        + photoFormat: normal (string, required, default)
 + slowMotion (object, required)
        + recordingFormat: 2032sq60 (string, required)
        + audioFormat: 48KAAC4 (string, required)
        + sensordataFormat: mode60fps (string, required)
        + liveviewFormat: 752sq15 (string, required)
        + photoFormat: normal (string, required)

### List all media profiles [GET]
+ Response 200 (application/json)
 + Attributes (Camera Media Profile Collection)

## Camera Media Profile [/360fly/camera/profiles/{name}]

Describes capture/encoding formats for recording, audio, sensordata, liveview, and photo.

+ Attributes (object)
 + recordingFormat: fullRes30 (string, required) - format of recorded video. See /camera/formats/video
 + audioFormat: 48KAAC4 (string, required) - format of encoded audio. See /camera/formats/audio
 + sensordataFormat: mode30fps (string, required) - format of sensor data for recordings and (future version) liveview stream. See /camera/formats/sensordata
 + liveviewFormat: 752sq15 (string, required) - format of liveview video stream. See /camera/formats/video
 + photoFormat: normal (string, required, default) - format of captured photos. See /camera/formats/photo
 
+ Parameters
 + name (required, string, `proMode`) the relevant profile
 
### Retrieve media profile details [GET]
+ Response 200 (application/json)
 + Attributes (Camera Media Profile)

### Create or modify media profile [PUT]
+ Attributes (object)
 + photoFormat: burstMode (string, optional, sample)

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (object)
        + recordingFormat: fullRes30 (string, required)
        + audioFormat: 48KAAC4 (string, required)
        + sensordataFormat: mode30fps (string, required)
        + liveviewFormat: 752sq15 (string, required)
        + photoFormat: burstMode (string, required, default)

### Remove media profile [DELETE]
+ Response 204

## Camera Formats Collection [/360fly/camera/formats]

The available media and sensordata formats. The various formats are used to compose a profile (see `/camera/profiles`). The formats are essentially configurations for underlying media/data encoder and capture applications.

* Both recording and liveview use video formats 

+ Attributes (object)
 + video (Camera Video Formats Collection, required) - list of available video formats
 + audio (Camera Audio Formats Collection, required) - list of available audio formats
 + sensordata (Camera Metadata Formats Collection, required) - list of available meta data formats
 + photo (Camera Photo Formats Collection, required) - list of available photo formats

### List all camera formats [GET]
+ Response 200 (application/json)
 + Attributes (Camera Formats Collection)

## Camera Video Formats Collection [/360fly/camera/formats/video]

+ Attributes (object)
 + fullRes30 (Camera Video Format, required, default) - Default recording video format
 + fullRes24 (object, required) - Full-res at 24fps. Gives more encoding bandwidth to liveview than fullRes30
        + resolution: 2880x2880 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 24 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 48000000 (number, required)
        + quant: 18 (number, required)
        + maxquant: 23 (number, required)
        + minquant: 0 (number, required)
        + maxframerate: 30 (number, required)
        + minframerate: 30 (number, required)
        + frontFacing: false (boolean, required)
 + 2816sq30 (object, required) - Slightly less than full-res video, but gives more encoding bandwidth to liveview than fullRes30
        + resolution: 2816x2816 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 24 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 60000000 (number, required)
        + quant: 18 (number, required)
        + maxquant: 23 (number, required)
        + minquant: 0 (number, required)
        + maxframerate: 30 (number, required)
        + minframerate: 30 (number, required)
        + frontFacing: false (boolean, required)
 + 1424sq24 (object, required, optional) - A high-res liveview format. Pairs well with fullRes24 recording format.
        + resolution: 1424x1424 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 24 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 11500000 (number, required)
        + quant: 18 (number, required)
        + maxquant: 23 (number, required)
        + minquant: 0 (number, required)
        + maxframerate: 30 (number, required)
        + minframerate: 30 (number, required)
        + frontFacing: false (boolean, required)
 + 752sq15 (object, required) - A low encoding bandwidth liveview format. Yields a large amount of encoding bandwidth to recording.
        + resolution: 752x752 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 15 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 2000000 (number, required)
        + quant: 18 (number, required)
        + maxquant: 23 (number, required)
        + minquant: 0 (number, required)
        + maxframerate: 30 (number, required)
        + minframerate: 30 (number, required)
        + frontFacing: false (boolean, required)
 + 1584p30 (object, required) - The maximum resolution for a front-facing recording format at 30fps
        + resolution: 2816x1584 (string, required)
        + resize: crop (string, required)
        + codec: h264 (string, required)
        + framerate: 30 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 33000000 (number, required)
        + quant: 18 (number, required)
        + maxquant: 23 (number, required)
        + minquant: 0 (number, required)
        + maxframerate: 30 (number, required)
        + minframerate: 30 (number, required)
        + frontFacing: true (boolean, required)
 + 1440p30 (object, required) - Alternative front-facing recording format
        + resolution: 2560x1440 (string, required)
        + resize: crop (string, required)
        + codec: h264 (string, required)
        + framerate: 30 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 27000000 (number, required)
        + quant: 18 (number, required)
        + maxquant: 23 (number, required)
        + minquant: 0 (number, required)
        + maxframerate: 30 (number, required)
        + minframerate: 30 (number, required)
        + frontFacing: true (boolean, required)
 + 2032sq60 (object, required) - The max resolution recording format at 60fps
        + resolution: 2032x2032 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 60 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 60000000 (number, required)
        + quant: 18 (number, required)
        + maxquant: 23 (number, required)
        + minquant: 0 (number, required)
        + maxframerate: 30 (number, required)
        + minframerate: 30 (number, required)
        + frontFacing: false (boolean, required)
 + 720p15 (object, required) - a front-facing liveview format   
        + resolution: 1280x720
        + resize: crop (string, required)
        + codec: h264 (string, required)
        + framerate: 60 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 250000 (number, required)
        + quant: 18 (number, required)
        + maxquant: 23 (number, required)
        + minquant: 0 (number, required)
        + maxframerate: 30 (number, required)
        + minframerate: 30 (number, required)
        + frontFacing: true (boolean, required)
 + 1504sq60 (object, required) - a lower resolution 60 fps recording format
        + resolution: 1504x1504 (string, required)
        + resize: scale (string, required)
        + codec: h264 (string, required)
        + framerate: 60 (number, required)
        + keyinterval: 30 (number, required)
        + ratecontrol: CVBR (string, required)
        + bitrate: 33000000 (number, required)
        + quant: 18 (number, required)
        + maxquant: 23 (number, required)
        + minquant: 0 (number, required)
        + maxframerate: 30 (number, required)
        + minframerate: 30 (number, required)
        + frontFacing: false (boolean, required)
        
### List all video formats [GET]
+ Response 200 (application/json)
 + Attributes (Camera Video Formats Collection)
         
## Camera Video Format [/360fly/camera/formats/video/{name}]

Format of encoded video for recording and liveview

+ Attributes (object)
 + resolution: 2880x2880 (string, required) - resolution of encoded video
 + resize: scale (string, required) - resize method. options: none, scale, crop
 + codec: h264 (string, required)
 + framerate: 30 (number, required) - target framerate of encoded video (FPS)
 + keyinterval: 30 (number, required) - framecount between keyframes
 + ratecontrol: CVBR (string, required) - bit rate control method. options: NONE, VQCB, CQCB, CVBR, ADPT
 + bitrate: 60000000 (number, required) - maximum or target bitrate (depending on ratecontrol)
 + quant: 18 (number, required) - target quantization. Ranges 0~51. Higher yields more compression.
 + maxquant: 23 (number, required) - max quantization
 + minquant: 0 (number, required) - min quantization
 + maxframerate: 30 (number, required) - max framerate of encoded video (FPS). min 15 FPS
 + minframerate: 30 (number, required) - min framerate of encoded video (FPS). min 15 FPS
 + frontFacing: false (boolean, required, default) - Front facing mode flag. False implies default projection. True implies planar projection.

+ Parameters
 + name (required, string, `fullRes30`) the relevant video format
 
### Retrieve video format details [GET]

+ Response 200 (application/json)
 + Attributes (Camera Video Format)

### Modify video format [PUT]

+ Attributes (object)
 + resolution: 2880x2880 (string)

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (Camera Video Format)

### Remove video format [DELETE]
+ Response 204

## Camera Audio Formats Collection [/360fly/camera/formats/audio]

+ Attributes (object)
 + 48KAAC4 (object, required) - default audio encoding format
        + bitrate: 6400 (number, required)
        + samplerate: 4800 (number, required)
        + codec: AAC4 (string, required)

### List all audio formats [GET]
+ Response 200 (application/json)
 + Attributes (Camera Audio Formats Collection)

## Camera Audio Format [/360fly/camera/formats/audio/{name}]

+ Attributes (object)
 + bitrate: 64000 (required, number) - encoded audio bitrate
 + samplerate: 48000 (required, number) - rate audio is sampled
 + codec: AAC4 (required, string)
 
+ Parameters
 + name (required, string, `48KAAC4`) the relevant audio format
 
### Retrieve audio format details [GET]
+ Response 200 (application/json)
 + Attributes (Camera Audio Format)

### Modify audio format [PUT]
+ Attributes (object)
 + bitrate: 64000 (number, optional)

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (Camera Audio Format)

### Remove audio format [DELETE]
+ Response 204

## Camera Metadata Formats Collection [/360fly/camera/formats/sensordata]

+ Attributes (object)
 + mode30fps (Camera Metadata Format, required, default) - default sensor data capture behavior. Captures most sensors at 30fps
 + mode60fps (object, required) - capture most sensors at 60fps
        + accelMode: 2 (number, required)
        + accelRate: 60 (number, required)
        + gyroMode: 1 (number, required)
        + gyroRate: 60 (number, required)
        + magnetoMode: 1 (number, required)
        + magnetoRate: 60 (number, required)
        + gpsRate: 1 (number, required)

### List all sensordata formats [GET]
+ Response 200 (application/json)
 + Attributes (Camera Metadata Formats Collection)

## Camera Metadata Format [/360fly/camera/formats/sensordata/{name}]

Format of sensordata. Effectively a configuration for underlying sensors, events, etc.

+ Attributes (object)
 + accelMode: 2 (number, required) -  accelerometer operating mode in g's. In this case: 2g mode
 + accelRate: 30 (number, required) - accelerometer sample rate, in samples per second
 + gyroMode: 1 (number, required) - gyroscope operating mode
 + gyroRate: 30 (number, required) - gyroscope sample rate, in samples per second
 + magnetoMode: 1 (number, required) - magnetometer operating mode
 + magnetoRate: 30 (number, required) - magnetometer sample rate, in samples per second
 + gpsRate: 1 (number, required) - gps sample rate, in samples per second
 
+ Parameters
 + name (required, string, `mode30fps`) the relevant sensordata format
 
### Retrieve sensordata format details [GET]
+ Response 200 (application/json)
 + Attributes (Camera Metadata Format)

### Modify sensordata format [PUT]
+ Attributes (object)
 + accelRate: 30 (number)

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (Camera Metadata Format)

### Remove sensordata format [DELETE]
+ Response 204

## Camera Photo Formats Collection [/360fly/camera/formats/photo]

+ Attributes (object)
 + normal (Camera Photo Format, required, default)
 + burstMode (object, required, sample)
        + resolution: 3456x3456 (string, required, default)
        + burst: true (boolean, required, default)
        + duration: 1 (number, required, default)

### Retrieve Camera Photo Formats [GET]
+ Response 200 (application/json)
 + Attributes (Camera Photo Formats Collection)

## Camera Photo Format [/360fly/camera/formats/photo/{name}]

+ Attributes (object)
 + resolution: 3456x3456 (string, required, default) - resolution of photo
 + burst: false (boolean, required, default) - Toggle burst mode
 + duration (number, optional, default) - How long, in seconds, to take burst photos. Applies to burst mode only.

+ Parameters
 + name (required, string, `normal`) the relevant photo format

## Liveview [/360fly/camera/liveview]

Status and settings for the 360fly `rtsp` stream.

+ Attributes
 + url: rtsp://fly.local/live1.sdp (string, required, sample) - liveview rtsp url
 + projection (Projection, required, default) - the projection data of liveview video

### Retrieve liveview settings [GET]
+ Response 200 (application/json)
 + Attributes (Liveview)

## Photo [/360fly/camera/photo]

### Take Photo [POST]

Returns empty response body with new photo's download link in `Location` header

+ Attributes (object)
 + burst: true (boolean, optional, sample) - Override current camera profile for this photo and take burst photo
 + duration: 3 (number, optional, sample) - Take 3 seconds worth of burst photos

+ Response 201
 + Header
 
            Location: /video/file/{photo.jpg}

## Tuning [/360fly/camera/tuning]

+ Attributes (object)
 + aeLock: false (boolean, required, default) - auto exposure lock/unlock
 + saturation: 100 (number, required, default) - image saturation. Range 0~200
 + maxIsoSensitivity: 8000 (number, required, default) - image iso (which adjusts gain). Range: 1000~64000
 + awbLock: false (boolean, required, default) - auto white balance lock/unlock
 + brightness: 100 (number, required, default) - image brightness. Range 0~200
 + aeCompensation: 100 (number, required, default) - compensation for auto exposure. Range: 50~200
 + contrast: 100 (number, required, default) - image contrast. Range 0~100
 + maxShutter: 30 (number, required, default) - max shutter speed. Shows denominator e.g. 30 implies 1/30 seconds. Must be >= 15

### Retrieve tuning settings [GET]
+ Response 200 (application/json)
 + Attributes (Tuning)

### Modify tuning settings [PUT]

+ Attributes (object)
 + aeLock: true (boolean, optional) - Lock auto-exposure

+ Request (application/json)

+ Response 200 (application/json)
 + Attributes (object)
        + aeLock: true (boolean, required)
        + saturation: 100 (number, required)
        + maxIsoSensitivity: 8000 (number, required)
        + awbLock: false (boolean, required)
        + brightness: 100 (number, required)
        + aeCompensation: 100 (number, required)
        + contrast: 100 (number, required)
        + maxShutter: 30 (number, required)
 
## Projection [/360fly/camera/projection]

Camera's default projection

+ Attributes (object)
 + type: radial (string, required, default) - class of projection
 + radialMapping: ftheta (string, required, default) - name of mapping used to map angle to radius on a radial capture image
 + outerAngle: 120 (number, required, default) - Half of the vertical field of view. The max of the radialMapping's domain.
 + centerRadius: 0.5 0.5 0.5 0.5 (string, required, default) - The location and size of radial image in camera's normalized sensor coordinates

### Set Projection [PUT]

For setting projection at manufacturing. Can only be done once.

+ Request (application/json)
 + Attributes (Projection)

+ Response 200 (application/json)
 + Attributes (Projection)



